# Generated by Django 3.2 on 2022-03-05 19:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[(api.models.DeviceChoice['Mobile'], 'Mobile'), (api.models.DeviceChoice['Laptop'], 'Laptop')], max_length=5)),
            ],
        ),
    ]
