# Generated by Django 3.2 on 2022-03-05 19:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='device_type',
            field=models.CharField(blank=True, choices=[(api.models.DeviceChoice['Mobile'], 'Mobile'), (api.models.DeviceChoice['Laptop'], 'Laptop')], max_length=6, null=True),
        ),
    ]
